# Generated by Django 4.1.7 on 2023-05-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_modelo2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modelo2',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
    ]
