name: Deploy to ECR

# son las condiciones paraque se ejecute automaticamente
on:
  push:
    branches: 
      - main
    paths:
      - app/**
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: public.ecr.aws/o1w2h9a8
  ECR_REPOSITORY: blogs-app-dev
  IMAGE_TAG: ${{ github.sha }}
  DEPLOYMENT_NAME: web-django-deployment
  NAMESPACE: test2
  # CLUSTER_NAME: eks-dev-cluster


jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest # ejecutar con 

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1

    - name: login to Amazon public
    #aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/o1w2h9a8
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY

  
    - name: Download environment file from S3
      env:
        S3_BUCKET_URL: s3://blogs-app-dev/.env # ruta s3
        #             :
        TARGET_PATH: . # me toma la ruta de donde estoy
      run: aws s3 cp $S3_BUCKET_URL $TARGET_PATH # valla a s3 copie el dato de esta ruta y pongalo aqui donde estoy 


    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    # - name: update deployment
    #   run: kubectl rollout restart deployment $DEPLOYMENT_NAME -n $NAMESPACE


    # - name: Run update deployment
    #   uses: nikosch86/github-action-eks-kubectl@main
    #   with:
    #     command: rollout restart deploy $DEPLOYMENT_NAME -n $NAMESPACE
    #   env:
    #     EKS_CLUSTER: $CLUSTER_NAME
         

